### ISSUE TITLE
[Bug] Access Denied on mobile

### ISSUE THREAD

**Issue by iamrecursion** [fenjalien/obsidian-typst#53] opened 2024-06-10 15:36 UTC
Whenever trying to load a package on mobile, even one that is actually downloaded into the packages folder, I get the following error

```
iled to load file (access denied)
   ╭─[/Scratchpad.md:3:9]
   │
 3 │ #import "@preview/cetz:0.2.2"           as draw    // Diagrams with code (like TikZ)
   │ 
   │ Help: cannot read file outside of project root you can adjust the project root with the --root argument
───╯
```

Yes, it actually appears cut off like this. I have confirmed that the file is actually downloaded using the vault API.

This is on iOS specifically, with the latest stable version of Obsidian.

**Comment by d-kaue** [comment] 2024-06-19 11:21
Hi @iamrecursion, I think I've found the cause of the problem, but I don't have an iOS device to test.

If you could edit the file `main.js` in the directory `.obsidian/plugins/typst/` and go to line 844.

Replace `require("path").isAbsolute(path)` with `false`.

The change should be equal this:
```diff
- if (require("path").isAbsolute(path)) {
+ if (false) {
```

Save and reload the plugin.

**Comment by iamrecursion** [comment] 2024-06-19 14:31
This does not appear to change anything unfortunately.

**Comment by fenjalien** [comment] 2024-06-19 16:39
I've just noticed this is a duplicate of #38, failing to read files on iOS is a known bug and I still don't have any access to an Apple device to properly debug and resolve this problem.

**Closed by fenjalien** 2024-06-19 16:39 UTC
Labels: bug
